config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user_preferences, path: 'Fragebogen'

  root to: "static_content#show"

  devise_for :users, path: 'ops', controllers: {
               # ROOT hat einen harten Link auf /ops/registrieren/sign_up
               registrations:  'users/registrations',
               confirmations:  'users/confirmations',
             }, path_names: {
               sign_in: 'anmelden',
               sign_out: 'abmelden',
               confirmation: 'bestätigen',
               registration: 'registrieren',
               edit: 'ändern'
             }

  resources :captcha_templates

  resources :user_admin, only: [:index, :update]

  get 'emails', to: 'emails#index'
  get '4admin', to: 'status#admin'

  resources :stations, only: [:index] do
    get '4op', to: 'status#op'
    get 'upcoming', to: 'status#upcoming'
    get 'past', to: 'status#past'
    resources :reservations, only: [:index, :new, :create]
  end

  # Shallow on these:
  resources :reservations, only: [:show, :edit, :update, :destroy] do
    resources :log_file_records, only: [:index, :new, :create]
  end

  resources :log_file_records, only: [:show, :edit, :update, :destroy]

  get '(:slug)', to: "static_content#show"
end

app/models/reservation.rb
# coding: utf-8
class StartsBeforeEndValidator < ActiveModel::Validator
  def validate(res)
    if res.end_time <= res.start_time
      res.errors[:end_time] << "Nutzung sollte nicht aufhören, ehe sie angefangen hat."
    end
  end
end

class ValidateDecisionWantedNotLaterThanStart < ActiveModel::Validator
  def validate(res)
    dw = res.decision_wanted
    if dw && res.start_time < dw
      res.errors[:base] << "Erst erfahren wollen, ob's klappt, nachdem die Nutzung schon angefangen hat? Das ist unsinnig."
    end
  end
end

class WithinStationAvailabilityValidator < ActiveModel::Validator
  def validate(res)
    if res.start_time < res.station.earliest_start
      res.errors[:start_time] << "Die Nutzung kann nicht anfangen ehe #{res.station.name} verfügbar wird, nämlich #{res.station.earliest_start}."
    end
    if res.station.latest_end < res.end_time
      res.errors[:end_time] << "Die Nutzung kann nicht länger dauern als die #{res.station.latest_end} " +
        "endende Verfügbarkeit von #{res.station.name}."
    end
  end
end

class NotTooLongValidator < ActiveModel::Validator
  def validate(res)
    if res.start_time + Reservation::MAX_DURATION < res.end_time
      res.errors[:base] << "Eine Nutzung kann für maximal #{Reservation::MAX_DURATION / 3600.0} Stunden beantragt werden."
    end
  end
end

class ExactlyOneLastEventValidator < ActiveModel::Validator
  def validate(res)
    unless 1 == res.reservation_events.to_a.find_all{|ev| ev.last_for_reservation}.size
      res.errors[:base] << "Interner Fehler: Nutzung #{res.id} hat gleichzeitig zwei letzte Änderungen."
    end
  end
end

class UserProvidesAdifLogValidator < ActiveModel::Validator
  def validate(res)
    unless (res.user.user_preference && res.user.user_preference.log_provide_adif)
      res.errors[:base] << "Reservierungen nur für OPs, die (laut Fragebogen) ADIF-Logs bereitstellen."
    end
  end
end

class NoDoubleAssignmentValidator < ActiveModel::Validator
  def validate(res)
    critical_states = [:granted]
    my_state = res.present_state
    if critical_states.include? my_state
      r =  Reservation.
          find_overlapping(res.station_id, res.start_time, res.end_time).
          find_all {|r| r.id != res.id}.
          find {|r| critical_states.include? r.present_state}
      if r
        res.errors[:base] << "Interner Fehler: Konflikt mit Nutzung #{r.id}. Dies sollte nicht auftreten!"
      end
    end
  end
end

class ReservationStateChangeIllegalException < RuntimeError
  
end

class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :station
  has_many :reservation_events, -> { order "id ASC" }, autosave: true
  has_many :log_file_records, -> {order "id ASC" }, autosave:true

  validates :start_time, :end_time, :user, :station, presence: true
  validates_with StartsBeforeEndValidator
  validates_with WithinStationAvailabilityValidator
  validates_with NotTooLongValidator
  validates_with NoDoubleAssignmentValidator
  validates_with ExactlyOneLastEventValidator
  validates_with ValidateDecisionWantedNotLaterThanStart
  validates_with UserProvidesAdifLogValidator

  MAX_DURATION = 50 * 3600

  CONFLICTING_STATES = [:requested, :granted].freeze

  def self.make(user, station, start_time, end_time, importance, op_publish, comment, decision_wanted, qrg_mode)
    res = user.reservations.build(station: station, start_time: start_time.getutc, end_time: end_time.getutc)
    res.add_event(:requested, false, importance, op_publish, comment, decision_wanted, qrg_mode)
    res
  end

  def add_event(event_type, is_admin, importance, op_publish, comment, decision_wanted, qrg_mode)
    ets = event_type.to_sym
    ev = nil
    lev = self.last_event
    if lev
      if lev.choices_next_state(is_admin, not(log_file_records.empty?)).include?(ets) || lev.event_type == ets.to_s
        ev = self.reservation_events.build(station_id: self.station_id,
                                           reservation: self,
                                           event_type: ets,
                                           decision_wanted: decision_wanted,
                                           op_publish: op_publish,
                                           importance: importance,
                                           comment: comment,
                                           qrg_mode: qrg_mode,
                                           last_for_reservation: true)
        lev.last_for_reservation = false
      else
        raise ReservationStateChangeIllegalException.new("Cannot reach \"#{ets}\" from \"#{self.present_state}\" as is_admin? == #{is_admin}.")
      end
    else
      if ets == :requested
        ev = self.reservation_events.build(station_id: self.station_id,
                                           reservation: self,
                                           event_type: ets,
                                           decision_wanted: decision_wanted,
                                           op_publish: op_publish,
                                           importance: importance,
                                           comment: comment,
                                           qrg_mode: qrg_mode,
                                           last_for_reservation: true)
      else
        raise ReservationStateChangeIllegalException.new("Cannot start with state \"#{ets}\"")
      end
    end
    ev
  end

  def self.find_by_id_full(id)
    Reservation.includes(:user, :station, :reservation_events, :log_file_records).find(id)
  end

  def self.find_overlapping(my_station_id, my_start_time, my_end_time)
    Reservation.includes(:user, :station, :reservation_events).
      where(":my_station_id = station_id and :min_start_time <= start_time and start_time < :my_end_time and (" +
            # Overlap if their start time is in my interval:
            "(:my_start_time <= start_time and start_time < :my_end_time) or " +
            # Overlap if their end time is in my interval:
            "(:my_start_time < end_time and end_time <= :my_end_time) or " + 
            # Overlap if my start time is in their interval:
            "(start_time <= :my_start_time and :my_start_time < end_time)" +
            # No need to check if my end_time is in their interval:
            # If their start time is earlier than mine, my start time is in their interval;
            # or if their start time is later than mine, their start time is in my interval.
            ")", {
              my_station_id: my_station_id,
              min_start_time: my_start_time - Reservation::MAX_DURATION,
              my_start_time: my_start_time,
              my_end_time: my_end_time
            }).
      all.
      to_a.sort do |a, b|
        st = a.start_time <=> b.start_time
        st == 0 ? a.end_time <=> b.end_time : st
      end
  end

  def self.wait_for_log(station_id, user_id, now = Time.now.getutc)
    wait_for_logs_incomplete =
      Reservation.joins(:reservation_events).
      where("reservation_events.station_id = :my_station_id and reservation_events.last_for_reservation = true and " +
            "(reservation_events.event_type = :my_terminated or " +
            "  (reservation_events.event_type = :my_granted and reservations.end_time <= :my_now)) and " + 
            "reservations.user_id = :my_user_id and reservations.station_id = :my_station_id",
            {my_station_id: station_id, my_user_id: user_id, my_now: now,
             my_terminated: ReservationEvent.event_types[:terminated],
             my_granted: ReservationEvent.event_types[:granted]})

    Reservation.includes(:reservation_events).
      where("id in (:res_ids)", {res_ids: wait_for_logs_incomplete.to_a.map{|r| r.id}}).
      order(:start_time, :end_time)
  end

  def self.wait_for_grants(station_id, user_id, now = Time.now.getutc)
    wait_for_grants_incomplete =
      Reservation.
      joins(:reservation_events).
      where("reservation_events.station_id = :my_station_id and reservation_events.last_for_reservation = true and " +
            "reservation_events.event_type = :my_requested and " + 
            "reservations.user_id = :my_user_id and reservations.station_id = :my_station_id",
            {my_station_id: station_id, my_user_id: user_id, my_requested: ReservationEvent.event_types[:requested]})

    wait_for_grants =
      Reservation.includes(:reservation_events).
      where("id in (:res_ids)", {res_ids: wait_for_grants_incomplete.to_a.map{|r| r.id}}).
      to_a.
      sort do |r1, r2|
      dw = r1.decision_wanted <=> r2.decision_wanted
      dw == 0 ? r1.start_time <=> r2.start_time : dw
    end

    wait_for_grants.reduce [[],[]] do |wn, r|
      if r.end_time <= now
        wn[1] << r
      else
        wn[0] << r
      end
      wn
    end
  end

  def self.canceled(station_id, user_id)
    activation_ids =
      Reservation.
      joins(:reservation_events).
      where("reservation_events.station_id = :my_station_id and reservation_events.last_for_reservation = true and " +
            ":my_canceled = reservation_events.event_type and " + 
            "reservations.user_id = :my_user_id and reservations.station_id = :my_station_id",
            {
                my_station_id: station_id,
                my_user_id: user_id,
                my_canceled: ReservationEvent.event_types[:canceled]
            }
           ).to_a.map{|r| r.id}

      Reservation.includes(:reservation_events).
      where("id in (:res_ids)", {res_ids: activation_ids}).
      order(:start_time, :end_time).
      to_a
  end

  def self.activations(station_id, user_id, now = Time.now.getutc)
    activation_ids =
      Reservation.
      joins(:reservation_events).
      where("reservation_events.station_id = :my_station_id and reservation_events.last_for_reservation = true and " +
            ":my_granted <= reservation_events.event_type and " + 
            "reservations.user_id = :my_user_id and reservations.station_id = :my_station_id",
            {

app/controllers/reservations_controller.rb
# coding: utf-8
class ReservationsController < ApplicationController
  before_action :set_station, only: [:create]
  before_action :set_admin_user
  before_action :authenticate_user!, except: [:index, :show]
  before_action :ensure_validated_user!, except: [:index, :show, :new]
  before_action :set_r, only: [:show, :edit, :update]
  before_action :set_may_change, only: [:show, :edit, :update]
  before_action :ensure_may_change!, only: [:update]
  before_action :set_may_log, only: [:show]
  before_action :list_next_event_types, only: [:edit, :update]

  def index
  end

  def new
    @page = "reservation.new"
    @validated_user = validated_user?
    @station = Station.find(params[:station_id])
    @reservation = Reservation.new
    next_week = Time.now.getutc + 7.days
    @reservation.station = @station
    @reservation.user = current_user
    @reservation.start_time = Time.new(next_week.year, next_week.month, next_week.day, next_week.hour, 0, 0, "+00:00")
    @reservation.end_time = @reservation.start_time + 7200
    def @reservation.op_publish
      user.user_preference && user.user_preference.default_op_publish
    end
    def @reservation.importance
      "normal"
    end
    def @reservation.decision_wanted
      s = (start_time - 4.days).getutc
      Time.new(s.year, s.month, s.day, 0, 0, 0, "+00:00")
    end
    def @reservation.qrg_mode
      "CW auf Kurzwelle"
    end
  end

  def create
    @validated_user = validated_user?
    rp = params[:reservation]
    @reservation = Reservation.make(
      current_user,
      @station,
      parse_time(rp[:start_time]),
      parse_time(rp[:end_time]),
      rp[:importance],
      rp[:op_publish].nil? ? false : rp[:op_publish] == "true",
      rp[:comment].present? ? rp[:comment] : nil,
      parse_time(rp[:decision_wanted]),
      rp[:qrg_mode].present? ? rp[:qrg_mode] : nil
    )
    @now = Time.now.getutc
    if @reservation.start_time <= @now
      @reservation.errors.add(:start_time,
                              "Reservierungen für die Vergangenheit sind zu aufwändig " +
                              "wegen der nötigen Zeitreisen." +
                              " (Notfalls Beicht-Nachricht an dj3ei schreiben.)")
      render :new
    else
      if @reservation.save
        if @reservation.start_time - Time.now.getutc < 3.days && @reservation.auto_accept_maybe
          redirect_to @reservation, \
          notice: "Folgende Reservierungsanfrage wurde im Schnellverfahren genehmigt:"
        else
          redirect_to @reservation, notice: "Folgende Reservierungsanfrage ist gespeichert:"
        end
      else
        render :new
      end
    end
  end

  def show
    @overlapping = Reservation.find_overlapping(@r.station_id, @r.start_time, @r.end_time).find_all{|r| r.id != @r.id}
  end

  def edit
    unless @may_change
      redirect_to reservation_path(@r)
    end
  end

  def update
    rp = params[:reservation]
    event_type = rp[:event_type].nil? ? @r.present_state : rp[:event_type]
    decision_wanted = parse_time(rp[:decision_wanted])
    pe = @r.last_event
    op_pub_in = rp[:op_publish]
    @r.add_event(event_type,
                 @admin_user,
                 nil_unless_changed(rp[:importance], @r.importance.to_s),
                 op_pub_in.nil? ? nil : nil_unless_changed(rp[:op_publish] == "true", @r.op_publish),
                 nil_unless_changed(rp[:comment], @r.comment),
                 nil_unless_changed(decision_wanted, @r.decision_wanted),
                 nil_unless_changed(rp[:qrg_mode], @r.qrg_mode))
    if @r.save
      redirect_to reservation_path(@r), notice: "Änderung ist gespeichert."
    else
      render :edit
    end
  end

  protected

  def nil_unless_changed(new, old)
    if new.nil? || new == old
      nil
    else
      logger.info("Changing for #{@r.id}: #{old} -> #{new}")
      new
    end
  end

  def set_r
    @r = Reservation.find_by_id_full(params[:id])
    @station = @r.station
  end

  def set_may_change
    @may_change = ((current_user && (current_user.id == @r.user.id)) || admin_user?) && @r.edit_makes_sense?
  end

  def set_may_log
    @may_log = ((current_user && (current_user == @r.user)) || admin_user?) && @r.expects_log?
  end

  def ensure_may_change!
    unless @may_change
      who = current_user ? current_user.callsign : "anonymous"
      logger.error("#{who} attempts to edit reservation #{@r.id}")
      raise NotOwnResources.new("#{who} attempts to edit reservation #{@r.id}")
    end
  end

  def list_next_event_types
    @next_event_types = @r.ui_choices(admin_user?)
  end

  def parse_time(hs)
    if hs
      y = hs[:year]
      mo = hs[:month]
      d = hs[:day]
      h = hs[:hour]
      mi = hs[:minute]
      if y.present? && mo.present? && d.present? && h.present?
        y = y.to_i
        mo = mo.to_i
        d = d.to_i
        h = h.to_i
        mi = mi.present? ? mi.to_i : 0
        Time.new(y, mo, d, h, mi, 0, "+00:00")
      else
        nil
      end
    else
      nil
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_comment.html.erb
<fieldset>
  <legend>Kommentar / sonstiges</legend>
  <p><%= text_field_tag("reservation[comment]", reservation.comment, size: 80) %></p>
  <p>Kontestteilnahme, *OTA, oder was sonst wichtig sein könnte.  Diese Info
    wird hier auf der Webseite veröffentlicht. (Kann freigelassen werden.)
  </p>
</fieldset>

app/views/reservations/_complain_on_error.html.erb
<% if reservation.errors.any? %>
  <div class="alert">
    <h2>Ihre Antwort kann so nicht gespeichert werden.</h2>

    <ul>
    <% reservation.errors.values.each do |message| %>
      <li><%= message.join " "  %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/reservations/_decision_wanted.html.erb
<% if reservation.last_event.nil? || reservation.present_state == :requested %>
<fieldset>
  <legend>Ob ich <%= station.name %> zu dieser Zeit nutzen kann, möchte ich möglichst wissen bis</legend>
  <table>
    <tbody>
      <tr><th>Jahr</th><th>Monat</th><th>Tag</th><th>Stunde</th><th></th></tr>
      <tr class="b-res_times">
        <%= render 'time', station: station, name: 'decision_wanted',
            selected: reservation.decision_wanted.getutc, omit_minute: true %>
        <td>UTC</td>
      </tr>
    </tbody>
  </table>
</fieldset>
<% end %>

app/views/reservations/_form.html.erb
<%= form_for(reservation, url: station_reservations_path(station_id: station.id), local: true) do |form| %>

<%= render 'complain_on_error', reservation: reservation %>

<fieldset>
  <legend>Ich möchte <%= station.name %> nutzen in der Zeit</legend>
  <table>
    <tbody>
      <tr><th></th><th>Jahr</th><th>Monat</th><th>Tag</th><th>Stunde</th><th>Minute</th><th></th></tr>
      <tr class="b-res_times">
        <td>von</td>
        <%= render 'time', station: station, name: 'start_time', selected: reservation.start_time.getutc, omit_minute: false %>
        <td>UTC</td>
      </tr>
      <tr class="b-res_times">
        <td>bis</td>
        <%= render 'time', station: station, name: 'end_time', selected: reservation.end_time.getutc, omit_minute: false %>
        <td>UTC.</td>
      </tr>
    </tbody>
  </table>
</fieldset>

<%= render 'importance', station: station, reservation: reservation %>

<%= render 'op_publish', station: station, reservation: reservation, user: user %>

<%= render 'decision_wanted', station: station, reservation: reservation %>

<%= render 'qrg_mode',  station: station, reservation: reservation %>

<%= render 'comment',  station: station, reservation: reservation %>

<p>Wenn die Nutzung genehmigt wird, verspreche ich</p>

<ul>
  <li>meine Reservierung möglichst umgehend zu stornieren, wenn ich doch nicht kann,</p>

  <li>nachher Auskunft darüber zu erteilen, welche
    <a href="https://lotw.arrl.org/lotw-help/submitting-qsos/#right-callsign">Variante</a> des Rufzeichens
    benutzt wurde. Wer etwas anderes will als <%= station.name %>,
    <%= station.name %>/p oder <%= station.name %>/m, klärt es bitte
    <em>vorher</em> mit <a href="mailto:dj3ei@d-70.de">mir</a>.</li>

  <li>
    ein vollständiges Log im ADIF-Format hier abzugeben (oder, bei
    Multi/Multi-Betrieb am selben Standort, auch mehrere).</li>

  <li>Bei unbewegtem Betrieb den Standort als sechsstelligen
    Maidenhead-Locator festzuhalten.</li>

  <li>Für jedes einzelne QSO, ob das QSO "normal" oder über Relais,
    Echolink, Packet Radio oder von einem Boot, Schiff oder einem
    Luftfahrzeug aus gemacht wurde (wichtig wegen der DXCC und DLD
    Diplome).</li>

</ul>

<p>Für ein vollständiges Log brauchen wir für jedes QSO mindestens:</p>

<ul>
  <li>Rufzeichen der Gegenstation,</li>
  <li>Anfangszeitpunkt des QSOs (in UTC),</li>
  <li>das Band,</li>
  <li>die Betriebsart und</li>
  <li>den von DR70BLN an die Gegenstation gegebenen Rapport.</li>
</ul>

<p>Das orientiert sich an den Erfordernissen für 
  <a href="https://lotw.arrl.org/lotw-help/submitting-qsos/">LotW</a>
  und für <a href="https://www.darc.de/index.php?eID=dumpFile&t=f&f=326596&token=ccd9a1e4c05aded25313ad25987588fbc0bb8fbd">QSL-Karten</a>.
</p>

<%= form.submit "Reservierung beantragen" %>
<% end %>

<p>Übrigens: Viele Angaben kann der verantwortliche OP nachträglich
  ändern, die zu QRG+Betriebsart sowie den Kommentar sogar während des
  bereits laufenden Betriebs.</p>

app/views/reservations/_importance.html.erb
<% if reservation.last_event.nil? || reservation.present_state == :requested %>
<fieldset>
  <legend>Dass die Nutzung zustande kommt, ist mir:</legend>
  <p><%= radio_button_tag("reservation[importance]", :badly_wanted, checked = reservation.importance == "badly_wanted") %>
  <%= label_tag("reservation_importance_badly_wanted", I18n.t("reservations.importance.badly_wanted"), class: "short") %>
  <%= radio_button_tag("reservation[importance]", :normal, checked = reservation.importance == "normal") %>
  <%= label_tag("reservation_importance_normal", I18n.t("reservations.importance.normal"), class: "short") %>
  <%= radio_button_tag("reservation[importance]", :unimportant, checked = reservation.importance == "unimportant") %>
  <%= label_tag("reservation_importance_unimportant", I18n.t("reservations.importance.unimportant"), class: "short") %></p>
  <p>Hier geht es um Konflikte, falls mehrere OPs die Station gleichzeitig an verschiedenen Standorten nutzen wollen.</p>
</fieldset>
<% end %>

app/views/reservations/_op_publish.html.erb
<fieldset>
  <legend>Mein Rufzeichen als verantwortlicher OP darf</legend>
  <%= radio_button_tag("reservation[op_publish]", "true", checked = reservation.op_publish) %>
  <%= label_tag("reservation_op_publish_true", "veröffentlicht werden.", class: "short") %>
  <%= radio_button_tag("reservation[op_publish]", "false", checked = not(reservation.op_publish)) %>
  <%= label_tag("reservation_op_publish_false", "nicht veröffentlicht werden.", class: "short") %>
  <span><a href="<%= edit_user_preference_path(user) + "#default_op_publish" %>">Standardwert ändern.</a></span>
</fieldset>

app/views/reservations/_qrg_mode.html.erb
<fieldset>
  <legend>QRG und Betriebsart</legend>
  <p><%= text_field_tag("reservation[qrg_mode]", reservation.qrg_mode, size: 80) %></p>
  <p>Falls vorhanden, wird dieser Hinweis hier auf der Webseite veröffentlicht, um
    denjenigen, die <%= station.name %> arbeiten wollen, die Suche zu
    erleichtern.  Auch im laufenden Betrieb änderbar.</p>
</fieldset>

app/views/reservations/show.html.erb
<p id="notice"<%= notice %></p>

<h1>Details einer Reservierungsanfrage für <%= @r.station.name %></h1>


<% if @r.present_state == :requested %>

<h2>Genehmigungsaussichten</h2>

<%
   cg = @r.conflict_grade
   case cg
   when :conflict_with_granted
   cl = "b-res_conflict__bad"
   when :conflict_with_more_important
   cl = "b-res_conflict__bad"
   when :conflict_with_equally_important
   cl = "b-res_conflict__uncertain"
   when :conflict_with_less_important
   cl = "b-res_conflict__no-problem"
   when :no_conflict
   cl = "b-res_conflict__no-problem"
   end
 %>

<p><span class="<%= cl%>"><%= I18n.t "reservations.conflict_grade.#{cg}" %></span></p>

<% end %>

<%= render 'reservation_details', reservation: @r, admin_user: @admin_user, current_user: @current_user %>

<%
log_button_class = "b-res_edit-button__left-in-row"
if @may_change
   log_button_class = "b-res_edit-button__in-row"

%>
   <%= form_tag edit_reservation_path(@r), method: "get", class: "b-res_edit-form__row" do %>
     <%= submit_tag "Ändern", class: "b-res_edit-button__left-in-row" %>
   <% end %>
<% end %>

<% if @may_log %>
  <%= form_tag new_reservation_log_file_record_path(@r), method: "get", class: "b-res_edit-form__row" do %>
    <%= submit_tag "Log abgeben", class: "#{log_button_class}" %>
  <% end %>
  <% unless @r.log_file_records.empty? %>
    <%= form_tag reservation_path(@r), method: "patch", class: "b-res_edit-form__row" do %>
      <%= hidden_field_tag name="reservation[event_type]", "log_received" %>
      <%= submit_tag value = "Keine weiteren Logs", class: "b-res_edit-button__in-row" %>
    <% end %>
  <% end %>
<% end %>

<% if not(@r.log_file_records.empty?) %>
<h2>Logs für diese Aktivierung</h2>

<p>Normalerweise ein Log, aber dürfen auch mehrere sein (z.B. bei MultiOp-Aktivierung am selben Standort).</p>

<ul>

<% @r.log_file_records.each do |lfr| %>

<li><a href="<%= edit_log_file_record_path(lfr) %>"><%= lfr.adif_log.blob.filename %></a>, hochgeladen <%= lfr.created_at %>.</li>

<% end %>

</ul>
<% end %>

<h2>Bisherige Historie dieser Anfrage</h2>

<table>
  <tbody>
  <%
    previous_event_type = nil
    @r.reservation_events.each do |re|
  %>
      <tr class="b-res_line__first"><td>Um</td><td><%= re.created_at %></td></tr>
      <% if previous_event_type != re.event_type %>
        <tr class="b-res_line__status"><td class="b-res_key">Status</td><td><%= I18n.t "reservations.state.#{re.event_type}" %></td></tr>
      <% end %>
      <% if re.comment.present? %><tr><td class="b-res_key">Kommentar</td><td><%= re.comment %></td></tr><% end %>
      <% if re.qrg_mode.present? %><tr><td class="b-res_key">qrg+mode</td><td><%= re.qrg_mode %></td></tr><% end %>
      <% unless re.op_publish.nil? %><tr><td class="b-res_key">OP veröffentlichbar</td><td><%= I18n.t "bool.#{re.op_publish}" %></td></tr><% end %>
      <% unless re.decision_wanted.nil? %><tr><td class="b-res_key">Entscheidung erbeten bis</td><td><%= re.decision_wanted %></td></tr><% end %>
      <% unless re.importance.nil? %>
        <tr><td class="b-res_key">Wichtigkeit</td><td><%= I18n.t "reservations.importance.#{re.importance}" %></td></tr>
      <% end %>
  <%
      previous_event_type = re.event_type      
    end
  %>
  </tbody>
</table>

<% unless @overlapping.empty? %>

<h2>Überlappende andere Anfragen</h2>

<p>Nicht erschrecken! Es ist ein gutes Zeichen, wenn mehrere zur
  gleichen Zeit aktiv werden wollen. Das bedeutet nur, dass die
  für das Rufzeichen zuständige Person eine Entscheidung treffen
  muss.</p>

<table>
  <tr>
    <th></th>
    <th>OP</th>
    <th class="b-res_otherkey">Status</th>
    <th>von</th>
    <th>bis</th>
    <th>W.</th>
  </tr>
  <% @overlapping.each do |other|
     imp = case other.importance
     when "badly_wanted" then "BW"
     when "normal" then "N"
     when "unimportant" then "U"
     else "?"
     end
   %>
  <% tr_class = other.relevant_for_op?(@r.start_time, @r.end_time) ? "b-res_row__relevant" : "b-res_row__irrelevant" %>
  <tr class="<%= tr_class %>">  
    <td><a href="<%= reservation_path(other) %>">Details</a></td>
    <td><%= other.op %></td>
    <td class="b-res_value"><%= I18n.t "reservations.shortstate.#{other.present_state}" %></td>
    <td class="b-res_value"><%= other.start_time %></td>
    <td class="b-res_value"><%= other.end_time %></td>
    <td class="b-res_value"><%= imp %></td>
  </tr>
  <% end %>
</table>

<% end %>