config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user_preferences, path: 'Fragebogen'

  root to: "static_content#show"

  devise_for :users, path: 'ops', controllers: {
               # ROOT hat einen harten Link auf /ops/registrieren/sign_up
               registrations:  'users/registrations',
               confirmations:  'users/confirmations',
             }, path_names: {
               sign_in: 'anmelden',
               sign_out: 'abmelden',
               confirmation: 'bestätigen',
               registration: 'registrieren',
               edit: 'ändern'
             }

  resources :captcha_templates

  resources :user_admin, only: [:index, :update]

  get 'emails', to: 'emails#index'
  get '4admin', to: 'status#admin'

  resources :stations, only: [:index] do
    get '4op', to: 'status#op'
    get 'upcoming', to: 'status#upcoming'
    get 'past', to: 'status#past'
    resources :reservations, only: [:index, :new, :create]
  end

  # Shallow on these:
  resources :reservations, only: [:show, :edit, :update, :destroy] do
    resources :log_file_records, only: [:index, :new, :create]
  end

  resources :log_file_records, only: [:show, :edit, :update, :destroy]

  get '(:slug)', to: "static_content#show"
end

app/controllers/status_controller.rb
# coding: utf-8
class StatusController < ApplicationController
  before_action :authenticate_user!, except: [:upcoming, :past]
  before_action :ensure_admin_user!, only: [:admin]
  before_action :set_station, except: [:admin]
  before_action :set_now

  QUICK_REFRESH = 60.seconds
  SLOW_REFRESH = 10.minutes

  def admin
    @users_to_confirm = User.includes(:user_preference).
                        joins(:user_preference).
                        where("users.verified_member = false and user_preferences.log_provide_adif = true").
                        order(:callsign)
    @stations = Station.all.order(:id).to_a
    @station2grant_wait = {}
    @stations.each do |station|
      waiting_ids = Reservation.joins(:reservation_events).
                where("reservation_events.station_id = :my_station_id and " +
                      "reservation_events.last_for_reservation = true and " +
                      "reservation_events.event_type = :my_requested and " + 
                      "reservations.station_id = :my_station_id",
                      {my_station_id: station.id,  my_requested: ReservationEvent.event_types[:requested]}).
                all.to_a.map{|r| r.id}
      waiting = Reservation.includes(:reservation_events, :station, :user).
                where("id in (:ids)",  {ids: waiting_ids}).
                all.to_a.
                sort do |r1, r2|
                  dw = (r1.decision_wanted <=> r2.decision_wanted)
                  dw == 0 ? (r1.start_time <=> r2.start_time) : dw
                end
      possibly_conflicting = Reservation.find_potentially_conflicting_reservations(waiting)
      @station2grant_wait[station.id] = waiting.find_all do |res|
        res.filter_worst_conflict(possibly_conflicting) != :granted
      end
    end
  end

  def op
    @statuspage = true
    if params[:user_id] && admin_user?
      @user = User.find(params[:user_id].to_i)
    else
      @user = current_user
    end
    @need_preference = @user.user_preference.nil?
    @need_log_promise = @need_preference || not(@user.user_preference.log_provide_adif)
    @wait_for_verify = not(@user.verified_member)
    if @need_preference || @need_log_promise || @wait_for_verify
      @about_to_activate =
        @past_activations =
        @wait_for_logs =
        @wait_for_grants =
        @not_granted =
        @canceled = []
    else
      @about_to_activate, @past_activations = Reservation.activations(@station.id, @user.id, @now)
      @canceled = Reservation.canceled(@station.id, @user.id)
      @wait_for_logs = Reservation.wait_for_log(@station.id, @user.id, @now)
      @wait_for_grants, @not_granted = Reservation.wait_for_grants(@station.id, @user.id, @now)
      @nothing_yet = not(@about_to_activate.any? || @past_activations.any? || @wait_for_logs.any? ||
                         @wait_for_grants.any? || @not_granted.any? || @canceled.any?)
    end
  end

  def past
    res_ids = ReservationEvent.
              where("reservation_events.station_id = :my_station_id and " +
                    "reservation_events.last_for_reservation = true and " +
                    "(" +
                    "reservation_events.event_type = :my_granted or " +
                    "reservation_events.event_type = :my_terminated or " +
                    ":my_log_received <= reservation_events.event_type" +
                    ")",
                    {
                      my_station_id: @station.id,
                      my_granted: ReservationEvent.event_types[:granted],
                      my_terminated: ReservationEvent.event_types[:terminated],
                      my_log_received: ReservationEvent.event_types[:log_received]
                    }).
              to_a.map{|rev| rev.reservation_id}
    @reservations = Reservation.includes(:user, :reservation_events).
                    where("id in (:my_ids) and start_time <= :now",
                          {my_ids: res_ids, now: @now}).
                    order(start_time: :desc).to_a
  end

  def upcoming
    if params[:refresh] != "true" && params[:refresh] != "false"
      redirect_to station_upcoming_path @station.id, refresh: "true"
    else
      refresh = params[:refresh] == "true"
      if params[:commit] || params[:utf8]
        # Reduce tail ?utf8=✓&refresh=false&commit=abschalten to ?refresh=false
        redirect_to station_upcoming_path @station.id, refresh: refresh
      else
        # Presently, this has ALL granted and requested events.
        # We rely on that later.
        res_ids = ReservationEvent.
          where("reservation_events.station_id = :my_station_id and " +
                "reservation_events.last_for_reservation = true and " +
                "(reservation_events.event_type = :my_granted or " +
                "reservation_events.event_type = :my_requested)",
                {my_station_id: @station.id,
                 my_requested: ReservationEvent.event_types[:requested],
                 my_granted: ReservationEvent.event_types[:granted]}).
          to_a.map{|rev| rev.reservation_id}
        
        wanted = Reservation.includes(:user, :reservation_events).
                    where("id in (:my_ids) and " +
                          ":my_now <= reservations.end_time and " + 
                          "reservations.station_id = :my_station_id",
                          {my_ids: res_ids,
                           my_now: @now,
                           my_station_id: @station.id}).
                    order(:start_time, :end_time).
                    to_a
        @upcoming = wanted.find_all {|res| :granted != res.filter_worst_conflict(wanted)}
        if refresh
          if @upcoming.empty?
            @status_autorefresh = SLOW_REFRESH
          else
            @first = @upcoming.first
            if @first.start_time <= @now
              @presently_active = true
              @status_autorefresh = QUICK_REFRESH
            else
              @status_autorefresh = (@first.start_time - @now + 1).to_i
              if @status_autorefresh < QUICK_REFRESH
                @status_autorefresh = QUICK_REFRESH
              elsif SLOW_REFRESH < @status_autorefresh
                @status_autorefresh = SLOW_REFRESH
              end
            end
          end
        end
      end
    end
  end

  protected

  def set_now
    @now = Time.now.getutc
  end
  
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/status/_autorefresh_head.html.erb
<meta http-equiv="refresh" content="<%= @status_autorefresh.to_i.to_s %>">

app/views/status/_old_activities.html.erb
<% if reservations.any? %>

<h2><%= headline %></h2>

<table>
  <tr>
    <th></th>
    <th>Status</th>
    <th>von</th>
    <th>bis</th>
  </tr>
  <% reservations.each do |other|   %>
  <tr>  
    <td class="b-status_value"><a href="<%= reservation_path(other) %>">Details</a></td>
    <td class="b-status_value"><%= I18n.t "reservations.past.shortstate.#{other.present_state}" %></td>
    <td class="b-status_value"><%= other.start_time %></td>
    <td class="b-status_value"><%= other.end_time %></td>
  </tr>
  <% end %>
</table>
<% end %>

app/views/status/_old_requested.html.erb
<% if reservations.any? %>

<h2><%= headline %></h2>

<table>
  <tr>
    <th></th>
    <th>von</th>
    <th>bis</th>
  </tr>
  <% reservations.each do |other|   %>
  <tr>  
    <td class="b-status_value"><a href="<%= reservation_path(other) %>">Details</a></td>
    <td class="b-status_value"><%= other.start_time %></td>
    <td class="b-status_value"><%= other.end_time %></td>
  </tr>
  <% end %>
</table>
<% end %>

app/views/status/_requested.html.erb
<% if reservations.any? %>

<h2><%= headline %></h2>

<table>
  <tr>
    <th></th>
    <th>Bescheid erbeten bis</th>
    <th>von</th>
    <th>bis</th>
    <th></th>
  </tr>
  <% reservations.each do |other|   %>
  <tr>  
    <td class="b-status_value"><a href="<%= reservation_path(other) %>">Details</a></td>
    <td class="b-status_value"><%= other.decision_wanted %></td>
    <td class="b-status_value"><%= other.start_time %></td>
    <td class="b-status_value"><%= other.end_time %></td>
    <td class="b-status-value"><%= I18n.t "reservations.conflict_grade_short.#{other.conflict_grade}" %></td>
  </tr>
  <% end %>
</table>

<p>Symbolerklärung:</p>

<table>
  <% [
     :no_conflict,
     :conflict_with_less_important,
     :conflict_with_equally_important,
     :conflict_with_more_important,
     :conflict_with_granted
     ].each do |c|  %>
  <tr>
    <td><%= I18n.t "reservations.conflict_grade_short.#{c}" %></td>
    <td><%= I18n.t "reservations.conflict_grade.#{c}" %></td>
  </tr>
  <% end %>
</table>

<% end %>

app/views/status/_reservation_details.html.erb
<%
   ui_state = reservation.ui_state now
   if :requested == ui_state
     tr_class = "b-status_row__requested"
     td_highlight_class = "b-status_field"
   elsif :currently_active == ui_state
     tr_class = "b-status_row__currently-active"
     td_highlight_class = "b-status_field__highlight"
   else
     tr_class = "b-status_row"
     td_highlight_class = "b-status_field"
   end
%>

<tr class="<%= tr_class %>">
  <td class="b-status_key">Status</td>
  <td>
    <span class="<%= td_highlight_class %>"><%= I18n.t "reservations.publishstate.#{ui_state}" %></span>
  </td>
</tr>
<% if reservation.qrg_mode.present? %>
  <tr class="<%= tr_class %>">
    <td class="b-status_key">qrg+mode</td>
    <td><%= reservation.qrg_mode %></td>
  </tr>
<% end %>
<% if reservation.comment.present? %>
  <tr class="<%= tr_class %>">
    <td class="b-status_key">Kommentar</td>
    <td><%= reservation.comment %></td>
  </tr>
<% end %>
<% if reservation.op_publish %>
  <tr class="<%= tr_class %>"><td class="b-status_key">OP</td><td><%= reservation.user.callsign %></td></tr>
<% end %>
<tr class="<%= tr_class %>"><td class="b-status_key">von</td><td><%= reservation.start_time %></td></tr>
<tr class="<%= tr_class %>"><td class="b-status_key">bis</td><td><%= reservation.end_time %></td></tr>
<tr class="<%= tr_class %>"><td class="b-status_key__lastline"><a href="<%= reservation_path(reservation) %>">Details</a></td></tr>

app/views/status/_reservation_details_sans_status.html.erb
<% if :currently_active == reservation.ui_state(now) %>

<tr class="b-status_row"><td class="b-status_key"></td><td>Aktivierung ist <span class="b-status_field__highlight"><%= I18n.t "reservations.publishstate.currently_active" %></span></td></tr>

<% end %>

<% if reservation.qrg_mode.present? %>
  <tr class="b-status_row">
    <td class="b-status_key">qrg+mode</td>
    <td><%= reservation.qrg_mode %></td>
  </tr>
<% end %>
<% if reservation.comment.present? %>
  <tr class="b-status_row">
    <td class="b-status_key">Kommentar</td>
    <td><%= reservation.comment %></td>
  </tr>
<% end %>
<% if reservation.op_publish %>
  <tr class="b-status_row"><td class="b-status_key">OP</td><td><%= reservation.user.callsign %></td></tr>
<% end %>
<tr class="b-status_row"><td class="b-status_key">von</td><td><%= reservation.start_time %></td></tr>
<tr class="b-status_row"><td class="b-status_key">bis</td><td><%= reservation.end_time %></td></tr>
<tr class="b-status_row"><td class="b-status_key__lastline"><a href="<%= reservation_path(reservation) %>">Details</a></td></tr>

app/views/status/admin.html.erb
<h1>Statusseite für Admin</h1>
<p>Stand <%= @now %></p>

<% if @users_to_confirm.any? %>

<h2>User warten auf <a href="<%= user_admin_index_path %>">Verifizierung</a></h2>

<table>
  <tr>
    <th>Call</th>
    <th>DOK</th>
    <th>Email</th>
  </tr>
  <%
     @users_to_confirm.each do |user|
     dok = user.user_preference ? user.user_preference.ov : "NONE"
   %>
  <tr>  
    <td class="b-status_value"><a href="<%= station_4op_path(1) %>?user_id=<%= user.id %>"><%= user.callsign %></a></td>
    <td class="b-status_value"><%= dok %></td>
    <td class="b-status_value"><%= user.email %></td>
  </tr>
  <% end %>
</table>

<% else %>

<p>Niemand wartet auf <a href="<%= user_admin_index_path %>">Verifizierung</a>. Gut.</p>

<% end %>

<% @stations.each do |station| %>

<% unless @station2grant_wait[station.id].empty? %>

<h2>Station <%= station.name %></h2>

<table>
  <tr>
    <th></th>
    <th>Call</th>
    <th>bis</th>
    <th>von</th>
    <th>bis</th>
    <th></th>
  </tr>
  <%
     @station2grant_wait[station.id].each do |other|
     user = other.user
   %>
  <tr>
    <td class="b-status_value"><a href="<%= reservation_path(other) %>">D.</a></td>
    <td class="b-status_value"><a href="<%= station_4op_path(other.station.id) %>?user_id=<%= user.id %>"><%= user.callsign %></a></td>
    <td class="b-status_value"><%= other.decision_wanted %></td>
    <td class="b-status_value"><%= other.start_time %></td>
    <td class="b-status_value"><%= other.end_time %></td>
    <td class="b-status-value"><%= I18n.t "reservations.conflict_grade_short.#{other.conflict_grade}" %></td>
  </tr>
  <% end %>
</table>

<% end # grant_wait not empty %>

<% end # station %>

app/views/status/op.html.erb
<h1>Statusseite für OP <%= @user.callsign %> bzgl. <%= @station.name %></h1>
<p>Stand <%= @now %></p>

<% if @need_preference %>

<h2><%= @station.name %> wartet auf den Fragebogen</h2>

<p>Wir warten noch darauf, dass Sie den <a href="<%= new_user_preference_path %>">Fragebogen</a>
  ausfüllen.</p>

<% elsif @need_log_promise %>

<h2><%= @station.name %> wartet auf Logabgabe-Zusage</h2>

<p>Wir warten noch auf Ihre Zusicherung im <a href="<%= edit_user_preference_path(current_user.user_preference) %>">Fragebogen</a>,
  nach dem Funkbetrieb ADIF-Logs abzugeben.</p>

<p>Wir sind <a href="/Rahmenbedingungen#logs">verpflichtet</a>, Logs
  für die Aktivitäten von <%= @station.name %> abzugeben.  Und alles andere
  als ADIF-Dateien macht erhebliche Mehrarbeit.
  (Aber reden Sie mit <a href="mailto:dj3ei@d-70.de">mir</a>,
  wenn Ihnen die Erstellung von ADIF-Logs tatsächlich Probleme bereitet.)</p>

<% elsif @wait_for_verify %>

<h2><%= @user.callsign %> wartet auf <a href="/Rufzeichenüberprüfung">Überprüfung</a></h2>

<p>Sie warten auf eine Überprüfung durch das
  <%= @station.name %>-Team.
  Die sollte in zwei, drei Tagen erledigt sein.  (Diese Überprüfung
  soll Rufzeichenmisbrauch verhindern.)</p>

<% else %>

<% if @about_to_activate.any? %>

<h2><%= @station.name %> rechnet mit Aktivierung</h2>

<p>Mit Hilfe des Links (erste Spalte) können Kommentar und QRG/Mode-Information
  jederzeit geändert werden, auch noch während der laufenden Aktion.</p>

<table>
  <tr>
    <th></th>
    <th>Status</th>
    <th>von</th>
    <th>bis</th>
  </tr>
  <% @about_to_activate.each do |other|   %>
  <tr>  
    <td class="b-status_value"><a href="<%= edit_reservation_path(other) %>">Details</a></td>
    <td class="b-status_value"><%= I18n.t "reservations.shortstate.#{other.present_state}" %></td>
    <td class="b-status_value"><%= other.start_time %></td>
    <td class="b-status_value"><%= other.end_time %></td>
  </tr>
  <% end %>
</table>

<% end %>

<% end %>

<% if @wait_for_logs.any? %>

<h2><%= @station.name %> wartet auf Logs</h2>

<p><span style="color: green;">Log abgeben geht jetzt!</span> Probleme bitte <a href="mailto:dj3ei@d-70.de">melden</a>!</p>

<table>
  <tr>
    <th></th>
    <th>von</th>
    <th>bis</th>
    <th></th>
  </tr>
  <% @wait_for_logs.each do |other| %>
  <tr>  
    <td><a href="<%= reservation_path(other) %>">Details</a></td>
    <td class="b-status_value"><%= other.start_time %></td>
    <td class="b-status_value"><%= other.end_time %></td>
    <td class="b-status_value"><a href="<%= new_reservation_log_file_record_path other %>">Logabgabe</a></td>
  </tr>
  <% end %>
</table>

<% end %>

<% if @nothing_yet %>

<h2>Sie sind am Zug!</h2>

<p>
  Wenn Sie Lust haben, <%= @station.name %> zu aktivieren,
  klicken Sie auf 
  "Nutzung <a href="<%= new_station_reservation_path(station_id: @station.id) %>"><%= @station.name %></a> anfragen".
</p>

<p>Wenn es damit Probleme gibt, helfe <a href="mailto:dj3ei@d-70.de">ich</a> (Andreas, DJ3EI) gerne.</p>

<% end %>

<%= render "requested", reservations: @wait_for_grants,
    headline: "#{@user.callsign} warted auf Genehmigung der #{@station.name}-Nutzung" %>

<%= render "old_activities", reservations: @past_activations,
    headline: "Frühere #{@station.name}-Nutzungen durch #{@user.callsign}" %>

<%= render "old_requested", reservations: @not_granted,
    headline: "Alte Anträge der #{@station.name}-Nutzung, die nicht genehmigt wurden" %>

<%= render "old_activities", reservations: @canceled,
    headline: "Anträge der #{@station.name}-Nutzung, die #{@user.callsign} zurückgezogen hat" %>

app/views/status/past.html.erb
<h1>Bisherige Aktivierungen von <%= @station.name %></h1>

<p>Stand: <%= @now %>.</p>

<table>

<% @reservations.each do |resv| %>

<%= render 'reservation_details_sans_status', reservation: resv, now: @now %>

<% end %>

</table>

app/views/status/upcoming.html.erb
<h1>Plan für <%= @station.name %></h1>

<p>Stand: <%= @now %>.</p>
<% if @status_autorefresh %>
<% end %>

<% if @status_autorefresh %>
<%= form_tag(station_upcoming_path(@station.id, refresh: "false"), method: "get") do %>
<fieldset>
  <legend>Seite lädt gegen <%= @now + @status_autorefresh %> den neuesten Stand nach.</legend>
  <%= hidden_field_tag name="refresh", "false" %>
  <%= submit_tag("Automatisches Nachladen abschalten.") %>
</fieldset>
<% end %>
<% else %>
<%= form_tag(station_upcoming_path(@station.id, refresh: "true"), method: "get") do %>
 <fieldset>
   <legend>Diese Seite kann den aktuellen Stand regelmäßig nachladen.</legend>
   <%= hidden_field_tag name="refresh", "true" %>
   <%= submit_tag("Automatisches Nachladen anschalten.") %>
 </fieldset>
<% end %>
<% end %>
<table>

<% @upcoming.each do |resv| %>

<%= render 'reservation_details', reservation: resv, now: @now %>

<% end %>

</table>