config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user_preferences, path: 'Fragebogen'

  root to: "static_content#show"

  devise_for :users, path: 'ops', controllers: {
               # ROOT hat einen harten Link auf /ops/registrieren/sign_up
               registrations:  'users/registrations',
               confirmations:  'users/confirmations',
             }, path_names: {
               sign_in: 'anmelden',
               sign_out: 'abmelden',
               confirmation: 'bestätigen',
               registration: 'registrieren',
               edit: 'ändern'
             }

  resources :captcha_templates

  resources :user_admin, only: [:index, :update]

  get 'emails', to: 'emails#index'
  get '4admin', to: 'status#admin'

  resources :stations, only: [:index] do
    get '4op', to: 'status#op'
    get 'upcoming', to: 'status#upcoming'
    get 'past', to: 'status#past'
    resources :reservations, only: [:index, :new, :create]
  end

  # Shallow on these:
  resources :reservations, only: [:show, :edit, :update, :destroy] do
    resources :log_file_records, only: [:index, :new, :create]
  end

  resources :log_file_records, only: [:show, :edit, :update, :destroy]

  get '(:slug)', to: "static_content#show"
end

app/models/captcha_template.rb
class CaptchaTemplate < ApplicationRecord

  def invalidate
    self.can_be_asked = false
    self.save
  end

  def self.give_captcha_to_ask
    # This is inefficient, CPU-wise. But it was efficient, programming time-wise.
    all_cts = CaptchaTemplate.where(can_be_asked: true).each.to_a

    # Use of the default random generator did not combine well with threads opened by Puma:
    # Early after application start, the same questions tended to be asked repeatedly.
    result = all_cts[Random.new.rand all_cts.length]

    result.asked = result.asked + 1
    begin
      result.save
    rescue ActiveRecord::StaleObjectError
      logger.warn "Captcha: Not counting one asked of #{result.id}"
    end
    result
  end

  def self.check_answer(id, answer, recursions_if_stale = 5)
    ct = CaptchaTemplate.find(id)
    ct.answered = ct.answered + 1
    regexp = Regexp.new("\\A#{ct.solution_regexp}\\z", Regexp::IGNORECASE)
    solved = regexp.match? answer
    if solved
      ct.answered_successfully = ct.answered_successfully + 1
    else
      logger.info "Captcha #{id} not solved, expected #{regexp}, saw \"#{answer}\"."
    end
    begin
      ct.save
    rescue ActiveRecord::StaleObjectError
      logger.info "Captcha: Handling a stale object error through recursion for #{ct.id}, #{solved}"
      if recursions_if_stale > 0
        self.check_answer(id, answer, recursions_if_stale - 1)
      else
        logger.warn "Captcha: Giving up on stale object error recursion for #{ct.id}, #{solved}"
      end
    end
    solved
  end
end

app/controllers/captcha_templates_controller.rb
class CaptchaTemplatesController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin_user!
  before_action :set_captcha_template, only: [:show, :edit, :update, :destroy]

  # GET /captcha_templates
  # GET /captcha_templates.json
  def index
    @captcha_templates = CaptchaTemplate.all
  end

  # GET /captcha_templates/1
  # GET /captcha_templates/1.json
  def show
  end

  # GET /captcha_templates/new
  def new
    @captcha_template = CaptchaTemplate.new
  end

  # GET /captcha_templates/1/edit
  def edit
  end

  # POST /captcha_templates
  # POST /captcha_templates.json
  def create
    @captcha_template = CaptchaTemplate.new(captcha_template_params)

    respond_to do |format|
      if @captcha_template.save
        format.html { redirect_to @captcha_template, notice: 'Captcha template was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /captcha_templates/1
  # PATCH/PUT /captcha_templates/1.json
  def update
    respond_to do |format|
      if @captcha_template.update(captcha_template_params)
        format.html { redirect_to @captcha_template, notice: 'Captcha template was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /captcha_templates/1
  # DELETE /captcha_templates/1.json
  def destroy
    info = if @captcha_template.invalidate
             {notice: 'Captcha template was successfully invalidated.'}
           end
    @captcha_template.errors.add(:can_be_asked, 'Just testing errors')
    respond_to do |format|
      format.html {
        redirect_to captcha_templates_url, info
      }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_captcha_template
      @captcha_template = CaptchaTemplate.find(params[:id])
    end

    def captcha_template_params
      params.require(:captcha_template).permit(:question, :solution_regexp)
    end
end

app/helpers/captcha_templates_helper.rb
module CaptchaTemplatesHelper
end

app/views/captcha_templates/_form.html.erb
<%= form_with(model: captcha_template, local: true) do |form| %>
  <% if captcha_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(captcha_template.errors.count, "error") %> prohibited this captcha_template from being saved:</h2>

      <ul>
      <% captcha_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>

  <div class="field">
    <%= form.label :solution_regexp %>
    <%= form.text_field :solution_regexp %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/captcha_templates/edit.html.erb
<h1>Editing Captcha Template</h1>

<%= render 'form', captcha_template: @captcha_template %>

<%= link_to 'Show', @captcha_template %> |
<%= link_to 'Back', captcha_templates_path %>

app/views/captcha_templates/index.html.erb
<h1>Captcha Templates</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Solution regexp</th>
      <th>Asked</th>
      <th>Answered</th>
      <th>Answered successfully</th>
      <th>Valid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @captcha_templates.each do |captcha_template| %>
      <tr>
        <td><%= captcha_template.question %></td>
        <td><%= captcha_template.solution_regexp %></td>
        <td><%= captcha_template.asked %></td>
        <td><%= captcha_template.answered %></td>
        <td><%= captcha_template.answered_successfully %></td>
        <td><%= captcha_template.can_be_asked %></td>
        <td><%= link_to 'Show', captcha_template %></td>
        <td><%= link_to 'Edit', edit_captcha_template_path(captcha_template) %></td>
        <td>
          <% if captcha_template.can_be_asked %>
              <%= form_tag captcha_template_path(captcha_template), method: "delete" do %>
                  <input type="submit" name="delete" value="invalidate" class="delete_button"/>
              <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Captcha Template', new_captcha_template_path %>

app/views/captcha_templates/new.html.erb
<h1>New Captcha Template</h1>

<%= render 'form', captcha_template: @captcha_template %>

<%= link_to 'Back', captcha_templates_path %>

app/views/captcha_templates/show.html.erb
<p>
  <strong>Question:</strong>
  <%= @captcha_template.question %>
</p>

<p>
  <strong>Solution regexp:</strong>
  <%= @captcha_template.solution_regexp %>
</p>

<p>
  <strong>Asked:</strong>
  <%= @captcha_template.asked %>
</p>

<p>
  <strong>Answered:</strong>
  <%= @captcha_template.answered %>
</p>

<p>
  <strong>Answered successfully:</strong>
  <%= @captcha_template.answered_successfully %>
</p>

<p>
  <strong>Can be asked:</strong>
  <%= @captcha_template.can_be_asked %>
</p>

<%= link_to 'Edit', edit_captcha_template_path(@captcha_template) %> |
<%= link_to 'Back', captcha_templates_path %>