config/routes.rb
# coding: utf-8
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :user_preferences, path: 'Fragebogen'

  root to: "static_content#show"

  devise_for :users, path: 'ops', controllers: {
               # ROOT hat einen harten Link auf /ops/registrieren/sign_up
               registrations:  'users/registrations',
               confirmations:  'users/confirmations',
             }, path_names: {
               sign_in: 'anmelden',
               sign_out: 'abmelden',
               confirmation: 'bestätigen',
               registration: 'registrieren',
               edit: 'ändern'
             }

  resources :captcha_templates

  resources :user_admin, only: [:index, :update]

  get 'emails', to: 'emails#index'
  get '4admin', to: 'status#admin'

  resources :stations, only: [:index] do
    get '4op', to: 'status#op'
    get 'upcoming', to: 'status#upcoming'
    get 'past', to: 'status#past'
    resources :reservations, only: [:index, :new, :create]
  end

  # Shallow on these:
  resources :reservations, only: [:show, :edit, :update, :destroy] do
    resources :log_file_records, only: [:index, :new, :create]
  end

  resources :log_file_records, only: [:show, :edit, :update, :destroy]

  get '(:slug)', to: "static_content#show"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>D wird 70</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%- # = javascript_include_tag "application", "data-turbolinks-track": "reload" -%>
    <% if @status_autorefresh %>
      <%= render partial: "status/autorefresh_head" %>
    <% end %>
  </head>

  <body>

    <% if user_signed_in? %>
      <%= form_tag destroy_user_session_path, method: "delete", class: "tiny" do %>
      <aside class="b-app_user"><p>Sie sind hier angemeldet als <b><%= current_user.callsign %></b>.</p>
          <%= render partial: "partials/status_link" %>
          <%= render partial: "partials/questionaire_nudge" %>
          <%= submit_tag "Abmelden", class: "logout" %>
      </aside>
      <% end %>
    <% else %>
        <aside class="user"><p>Sie sind hier zur Zeit nicht <%= link_to "angemeldet", user_session_path %>.</p></aside>
    <% end %>

    <% ################################################ %>
    <% #                                              # %>
    <% # KEEP IN SYNC with devise/sessions.html.erb ! # %>
    <% #                                              # %>
    <% ################################################ %>
    <%= render partial: "partials/flash" %>

    <main>
      <article>
        <%= yield %>
      </article>
    </main>
    <navigation>
      <h2>Navigation</h2>
      <p>Zum derzeitigen <a href="<%= station_upcoming_path(1) %>">Plan</a></p>
      <p>Zu den <a href="<%= station_past_path(1) %>">bisherigen Aktivierungen</a></p>
      <% if current_user %>
        <%= render partial: "partials/status_link" %>
        <%= render partial: "partials/questionaire_nudge" %>
        <% @stations.each do |station| %>
          <% unless @station == station && @page == "reservation.new" %>
          <p>Nutzung <a href="<%= new_station_reservation_path(station_id: station.id) %>"><%= station.name %></a> anfragen.</p>
        <%   end
        end %>
      <% else %>
        <p>Sie sind hier zur Zeit nicht <%= link_to "angemeldet", user_session_path %>.</p>
      <% end %>
      <p>Zurück zur <a href="/">Hauptseite</a>
        (oder unseren <a href="/Rahmenbedingungen">Rahmenbedingungen</a>).</p>
      <% unless @fragebogen_ergebnisseite %>
      <p>Zu den <a href="/Fragebogen">Fragebogen-Ergebnissen</a>.</p>
      <% end %>
      <% unless @datenschutz %>
        <p><a href="/Datenschutzerklärung">Datenschutzerklärung</a></p>
      <% end %>
      <% unless @lizenz %>
        <p><a href="/Lizenz">Lizenz und Link zum Sourcecode</a>.</p>
      <% end %>
      <% unless @impressum %>
        <p><a href="/Impressum">Impressum</a></p>
      <% end %>
    </navigation>
  </body>
</html>